/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef ANDROIDHELPER_AUTODEFS_H
#define ANDROIDHELPER_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_ANDROIDHELPER_NAME "AndroidHelper"
#define S3E_EXT_ANDROIDHELPER_HASH 0xe229d706

#ifdef S3E_EXT_REGISTER
#ifndef S3E_EXT_REGISTER_KEY
#define S3E_EXT_REGISTER_KEY(name, num, key) S3E_EXT_REGISTER(name, num)
#endif
S3E_EXT_REGISTER("AndroidHelper", 5)
#else

#endif /* S3E_EXT_REGISTER */
#endif /* !ANDROIDHELPER_AUTODEFS_H */
